server:
  port: 8001

spring:
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: dh-bbs-francis
  # 令牌有效期（默认30分钟）
  expireTime: 30