spring:
  datasource:
    username: root
    password: ma321388
    url: jdbc:mysql://localhost:3306/dh_bbs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #SpringBoot默认是不注入这些的，需要自己绑定
    #druid数据源专有配置
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存时间
    min-evictable-idle-time-millis: 300000
    #validation-query: SELECT 1 FROM sys_user
    #test-while-idle: true
    #test-on-borrow: false
    #test-on-return: false
    # 打开 PSCache，并且指定每个连接上 PSCache 的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
    filters: stat,wall
    # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
    connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

  redis:
    database: 2
    host: 120.24.223.36
    port: 6379
    password: ma321388
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms

mybatis-plus:
  mapper-locations: classpath*:org/francis/**/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_empty

logging:
  level:
    org:
      francis:
        dh:
          system:
            mapper: debug
          post:
            mapper: debug
